local g = vim.g
local api = vim.api
local keymap = vim.keymap

local wk = require("which-key")
function Modal(name, ...)
	require("telescope.builtin")[name](...)
end

-- Copilot swap tab since compe takes the tab key
g.copilot_no_tab_map = true
g.copilot_assume_mapped = true
keymap.set(
	"i",
	"<C-b>",
	'copilot#Accept("<Return>")',
	{ noremap = true, silent = true, expr = true, replace_keycodes = false }
)

keymap.set({ "n", "x" }, "p", "<Plug>(YankyPutAfter)")
keymap.set({ "n", "x" }, "P", "<Plug>(YankyPutBefore)")
keymap.set({ "n", "x" }, "gp", "<Plug>(YankyGPutAfter)")
keymap.set({ "n", "x" }, "gP", "<Plug>(YankyGPutBefore)")
keymap.set({ "n", "x" }, "<C-p>", "<Plug>(YankyCycleForward)", { noremap = false })
keymap.set({ "n", "x" }, "<C-M-p>", "<Plug>(YankyCycleBackward)", { noremap = false })
keymap.set("t", "<Esc>", [[<C-\><C-n>]], { noremap = true })

wk.add(
  {
    { "<C-[>", "<cmd>cprevious<CR>", desc = "prev item" },
    { "<C-\\>", "<cmd>copen<CR>", desc = "open coc" },
    { "<C-]>", "<cmd>cnext<CR>", desc = "next item" },
    { "<Down>", "1<C-w>-", desc = "dec height" },
    { "<Left>", "4<C-w><", desc = "dec width" },
    { "<Right>", "4<C-w>>", desc = "inc width" },
    { "<Up>", "1<C-w>+", desc = "inc height" },
    { "K", "<cmd>lua vim.lsp.buf.hover()<CR>", desc = "hover" },
    { "[d", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", desc = "prev-diag" },
    { "]d", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", desc = "next-diag" },
    { "g", group = "goto" },
    { "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>", desc = "declaration" },
    { "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", desc = "definition" },
    { "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", desc = "implementation" },
    { "gl", "<C-w>v<C-w>l<cmd>lua vim.lsp.buf.definition()<CR>", desc = "peek-definition-right" },
    { "go", "<C-w>v<C-w>lgf<CR>", desc = "peek-definition-right" },
    { "gr", "<cmd>lua vim.lsp.buf.references()<CR>", desc = "references" },
  }
)
wk.add({
    { "<leader><Tab>", group = "tabs" },
    { "<leader><Tab><Tab>", "<cmd>tabnext<cr>", desc = "next" },
    { "<leader><Tab>c", "<cmd>tabnew<cr>", desc = "new" },
    { "<leader><Tab>k", "<cmd>tabclose<cr>", desc = "kill" },
    { "<leader><Tab>n", "<cmd>tabnext<cr>", desc = "next" },
    { "<leader><Tab>p", "<cmd>tabprevious<cr>", desc = "previous" },
    { "<leader><enter>", "<cmd>lua Modal('command_history')<cr>", desc = "commands" },
    { "<leader><leader>", "<cmd>lua Modal('find_files')<cr>", desc = "find files" },
    { "<leader>`", group = "terminal" },
    { "<leader>``", "<cmd>ToggleTerm<cr>", desc = "toggle" },
    { "<leader>`c", '<cmd>lua require("toggleterm.terminal").Terminal:new({}).toggle()', desc = "create-new" },
    { "<leader>`f", '<cmd>ToggleTerm direction="float"<cr>', desc = "toggle-float" },
    { "<leader>`h", '<cmd>ToggleTerm direction="horizontal"<cr>', desc = "term-horisontal" },
    { "<leader>`l", "<cmd>ToggleTermSendCurrentLine<cr>", desc = "send-line" },
    { "<leader>`v", '<cmd>ToggleTerm direction="vertical"<cr>', desc = "term-vertical" },
    { "<leader>a", group = "all the rest" },
    { "<leader>aC", "<cmd>lua Modal('colorscheme')<cr>", desc = "theme" },
    { "<leader>aa", "<cmd>lua Modal('autocommands')<cr>", desc = "code-actions" },
    { "<leader>ab", "<cmd>lua Modal('buffers')<cr>", desc = "buffers" },
    { "<leader>ac", "<cmd>lua Modal('commands')<cr>", desc = "commands" },
    { "<leader>ae", "<cmd>Telescope emoji theme=ivy<cr>", desc = "emoji" },
    { "<leader>af", "<cmd>lua Modal('find_files')<cr>", desc = "files" },
    { "<leader>ag", "<cmd>ChatGPT<cr>", desc = "git" },
    { "<leader>am", "<cmd>lua Modal('man_pages')<cr>", desc = "man" },
    { "<leader>ao", "<cmd>lua Modal('vim_options')<cr>", desc = "vim options" },
    { "<leader>aq", "<cmd>lua Modal('marks')<cr>", desc = "marks" },
    { "<leader>ar", "<cmd>RoamOpenId<cr>", desc = "roam-goto-id" },
    { "<leader>b", group = "buffers" },
    { "<leader>bD", "<cmd>bd!<cr>", desc = "force delete" },
    { "<leader>bb", "<cmd>lua Modal('buffers')<cr>", desc = "list" },
    { "<leader>bd", "<cmd>bd<cr>", desc = "delete" },
    { "<leader>bn", "<cmd>bn<cr>", desc = "next" },
    { "<leader>bo", "<C-^><cr>", desc = "other" },
    { "<leader>bp", "<cmd>bp<cr>", desc = "previous" },
    { "<leader>br", "<cmd>e! %<cr>", desc = "refresh" },
    { "<leader>by", "<cmd>CopyBufferPath<cr>", desc = "copy-path" },
    { "<leader>c", group = "code" },
    { "<leader>cD", "<cmd>lua vim.lsp.buf.type_definition()<CR>", desc = "type-def" },
    { "<leader>cF", "<cmd>lua vim.lsp.buf.format { async = false }<CR>", desc = "format" },
    { "<leader>cS", "<cmd>lua require('luasnip.loaders').edit_snippet_files()<CR>", desc = "symbols" },
    { "<leader>ca", "<cmd>lua vim.lsp.buf.code_action()<CR>", desc = "actions" },
    { "<leader>cc", "<Plug>(comment_toggle_linewise_current)", desc = "comment" },
    { "<leader>ce", group = "errors" },
    { "<leader>ced", "<cmd>Trouble diagnostics<cr>", desc = "document" },
    { "<leader>cew", "<cmd>Trouble diagnostics<cr>", desc = "workspace" },
    { "<leader>cf", "<cmd>lua require('conform').format({lsp_format='fallback'})<CR>", desc = "format" },
    { "<leader>ch", "<cmd>lua vim.lsp.buf.signature_help()<CR>", desc = "help" },
    { "<leader>cq", "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>", desc = "loc-list" },
    { "<leader>cr", "<cmd>lua vim.lsp.buf.rename()<CR>", desc = "rename" },
    { "<leader>cs", "<cmd>lua vim.lsp.buf.document_symbol()<CR>", desc = "symbols" },
    { "<leader>cw", group = "workspace" },
    { "<leader>cwa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", desc = "wspace-add" },
    { "<leader>cwr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", desc = "wspace-rm" },
    { "<leader>d", group = "debug" },
    { "<leader>dD", ":lua require('dap').down()<CR>", desc = "frame-down" },
    { "<leader>dT", ":DapTerminate<CR>", desc = "debug-kill" },
    { "<leader>dU", ":lua require('dap').up()<CR>", desc = "frame-up" },
    { "<leader>db", ":Telescope dap list_breakpoints<CR>", desc = "breakpoints" },
    { "<leader>dc", ":lua require('telescope').extensions.dap.commands()<CR>", desc = "commands" },
    { "<leader>dd", ":DapToggleBreakpoint<CR>", desc = "bp-toggle" },
    { "<leader>df", ":Telescope dap frames<CR>", desc = "frames" },
    { "<leader>dh", "<C-w>h<cmd>q<cr>", desc = "win-del-left" },
    { "<leader>di", ":lua require('dap.ui.widgets').hover()<CR>", desc = "variables" },
    { "<leader>dj", "<C-w>j<cmd>q<cr>", desc = "win-del-bellow" },
    { "<leader>dk", "<C-w>k<cmd>q<cr>", desc = "win-del-above" },
    { "<leader>dl", "<C-w>l<cmd>q<cr>", desc = "win-del-right" },
    { "<leader>dr", group = "run" },
    { "<leader>drR", ":lua require('dap').repl.open()<CR>", desc = "repl" },
    { "<leader>drd", ":lua require('dap').continue()<CR>", desc = "continue" },
    { "<leader>drt", ":lua require('dap').run_to_cursor()<CR>", desc = "run-to-cursor" },
    { "<leader>ds", group = "step" },
    { "<leader>dsi", ":lua require('dap').step_into()<CR>", desc = "into" },
    { "<leader>dso", ":lua require('dap').step_over()<CR>", desc = "over" },
    { "<leader>dss", ":lua require('dap').step_over()<CR>", desc = "over" },
    { "<leader>dsu", ":lua require('dap').step_out()<CR>", desc = "out" },
    { "<leader>dt", ":DapToggleRepl<CR>", desc = "toggle-repl" },
    { "<leader>e", group = "eval" },
    { "<leader>ec", "<cmd>so ~/.config/nvim/init.lua<cr>", desc = "reload-config" },
    { "<leader>ee", ":w<cr>:so %<cr>", desc = "current file" },
    { "<leader>ek", "<cmd>e ~/.dotfiles/nvim/lua/halicea/keymaps.lua<cr>", desc = "keymaps" },
    { "<leader>ep", "<cmd>e ~/.dotfiles/nvim/lua/halicea/plugins.lua<cr>", desc = "plugins" },
    { "<leader>er", "<cmd>e! %<cr>", desc = "reload-current" },
    { "<leader>es", "<cmd>e ~/scratch.lua<cr>", desc = "scratch" },
    { "<leader>f", group = "file" },
    { "<leader>fc", "<cmd>lua Modal('commands')<cr>", desc = "commands" },
    { "<leader>ff", "<cmd>lua Modal('find_files', {no_ignore=true, no_ignore_parent=true, hidden=true})<cr>", desc = "find" },
    { "<leader>fn", "<cmd>new<cr><C-w>L", desc = "new" },
    { "<leader>fp", "<cmd>lua Modal('find_files',{search_dirs = {'~/.dotfiles'}})<cr>", desc = "dotfiles" },
    { "<leader>fr", "<cmd>lua Modal('oldfiles')<cr>", desc = "recent" },
    { "<leader>fs", "<cmd>w<cr>", desc = "file save" },
    { "<leader>ft", "<cmd>lua Modal('filetypes')<cr>", desc = "types" },
    { "<leader>g", group = "git" },
    { "<leader>gR", "<cmd>Git reset --hard HEAD<cr>", desc = "hard-reset" },
    { "<leader>gb", "<cmd>Git blame<cr>", desc = "blame" },
    { "<leader>gc", "<cmd>lua Modal('git_branches')<cr>", desc = "branches" },
    { "<leader>gf", "<cmd>Git fetch<cr>", desc = "fetch" },
    { "<leader>gg", "<cmd>Git<cr>", desc = "status" },
    { "<leader>gi", "<cmd>Git init<cr>", desc = "init" },
    { "<leader>gl", "<cmd>Git pull<cr>", desc = "pull" },
    { "<leader>gm", "<cmd>MerginalToggle<cr>", desc = "merge" },
    { "<leader>gp", "<cmd>Git push<cr>", desc = "push" },
    { "<leader>gs", "<cmd>Git<cr>", desc = "status" },
    { "<leader>h", group = "help" },
    { "<leader>hh", "<cmd>lua Modal('help_tags')<cr>", desc = "tags" },
    { "<leader>hm", "<cmd>lua Modal('keymaps')<cr>", desc = "keymaps" },
    { "<leader>ht", "<cmd>lua Modal('colorscheme')<cr>", desc = "colorscheme" },
    { "<leader>l", group = "lsp" },
    { "<leader>li", "<cmd>LspInstall<CR> ", desc = "install" },
    { "<leader>lk", "<cmd>LspStop<CR>", desc = "stop" },
    { "<leader>ll", "<cmd>LspInfo<CR>", desc = "status" },
    { "<leader>ls", "<cmd>LspStart<CR>", desc = "start" },
    { "<leader>m", group = "marks" },
    { "<leader>ma", "<cmd>lua require('dirmark').mark_cwd()<cr>", desc = "add cwd" },
    { "<leader>me", "<cmd>lua require('dirmark').open_marks_file()<cr>", desc = "dir marks file" },
    { "<leader>mm", "<cmd>lua require('dirmark').open()<cr>", desc = "dir mark" },
    { "<leader>mr", "<cmd>lua require('roam').search()<cr>", desc = "roam" },
    { "<leader>n", group = "open" },
    { "<leader>nd", "<cmd>lua require('dapui').toggle()<cr>", desc = "debug" },
    { "<leader>nf", "<cmd>NvimTreeFindFile<cr>", desc = "project find" },
    { "<leader>nm", "<cmd>MarkdownPreviewToggle<cr>", desc = "markdown" },
    { "<leader>nn", "<cmd>Oil<cr>", desc = "oil" },
    { "<leader>no", "<cmd>Oil<cr>", desc = "open" },
    { "<leader>np", "<cmd>NvimTreeToggle<cr>", desc = "project" },
    { "<leader>p", group = "plugins" },
    { "<leader>pc", "<cmd>Lazy clean<cr>", desc = "clean" },
    { "<leader>pi", "<cmd>Lazy sy<cr>", desc = "install" },
    { "<leader>pp", "<cmd>Lazy home<cr>", desc = "status" },
    { "<leader>pr", "<cmd>so ~/.config/nvim/init.lua<cr>", desc = "reload-config" },
    { "<leader>ps", "<cmd>Lazy sync<cr>", desc = "sync" },
    { "<leader>q", group = "quit" },
    { "<leader>qQ", "<cmd>qa!<cr>", desc = "quit all forced" },
    { "<leader>qa", "<cmd>qa<cr>", desc = "quit all" },
    { "<leader>qq", "<cmd>q<cr>", desc = "quit" },
    { "<leader>r", group = "repl/repeat" },
    { "<leader>ra", "ggVG:<C-U>REPLSendLines<cr><esc>", desc = "send-all" },
    { "<leader>rc", "<cmd>VimuxPromptCommand<cr>", desc = "prompt" },
    { "<leader>rd", "<cmd>VimuxCloseRunner<cr>", desc = "close" },
    { "<leader>re", "<cmd>@:<cr>", desc = "vim-last" },
    { "<leader>ri", "<cmd>VimuxInterruptRunner<cr>", desc = "interrupt" },
    { "<leader>rk", "<cmd>VimuxCloseRunner<cr>", desc = "kill" },
    { "<leader>ro", "<cmd>VimuxOpenRunner<cr>", desc = "open" },
    { "<leader>rr", "<cmd>VimuxRunLastCommand<cr>", desc = "run-last" },
    { "<leader>rs", "vip:<C-U>REPLSendLines<cr><esc>%", desc = "send-paragraph" },
    { "<leader>rt", "<cmd>VimuxTogglePane<cr>", desc = "toggle" },
    { "<leader>s", group = "search" },
    { "<leader>sd", "<cmd>lua Modal('live_grep')<cr>", desc = "in directory" },
    { "<leader>ss", "<cmd>lua Modal('current_buffer_fuzzy_find')<cr>", desc = "buffer" },
    { "<leader>t", group = "toggles" },
    { "<leader>t.", "<cmd>set list!<cr>", desc = "special-chars" },
    { "<leader>tL", "<cmd>set nu rnu!<cr>", desc = "line-numbers" },
    { "<leader>tb", group = "background" },
    { "<leader>tbD", "<cmd>colorscheme tokyonight-storm<cr><cmd>!~/.dotfiles/alacritty/alacritty-config -t tokyonightstorm<cr>", desc = "dark+term" },
    { "<leader>tbL", "<cmd>colorscheme newpaper<cr><cmd>!~/.dotfiles/alacritty/alacritty-config -t papercolor_light<cr>", desc = "light+term" },
    { "<leader>tbd", "<cmd>colorscheme nord<cr>", desc = "dark" },
    { "<leader>tbl", "<cmd><cmd>colorscheme leuven<cr>", desc = "light" },
    { "<leader>tbt", "<cmd>hi Normal guibg=NONE ctermbg=NONE<cr>", desc = "transparent" },
    { "<leader>td", "<cmd>lua require('dapui').toggle()<cr>", desc = "debug" },
    { "<leader>th", "<cmd>lua Modal('colorscheme')<cr>", desc = "colorscheme" },
    { "<leader>ti", "<cmd>IBLToggle<cr>", desc = "indent" },
    { "<leader>tl", "<cmd>set nu! rnu!<cr>", desc = "line-numbers" },
    { "<leader>tm", "<cmd>lua require('maximizer').toggle()<CR>", desc = "maximized" },
    { "<leader>ts", "<cmd>ToggleScratch<cr>", desc = "scratch" },
    { "<leader>tt", "<cmd>ToggleTerm<cr>", desc = "terminal" },
    { "<leader>tv", "<cmd>lua Toggle_venn()<CR>", desc = "toggle-venn" },
    { "<leader>tw", "<cmd>set wrap!<cr>", desc = "wrap" },
    { "<leader>tz", "<cmd>ZenMode<cr>", desc = "zen" },
    { "<leader>u", "<cmd>UndotreeToggle<cr>", desc = "undo tree" },
    { "<leader>w", group = "window" },
    { "<leader>wd", "<cmd>q<cr>", desc = "quit" },
    { "<leader>wh", "<C-w>h", desc = "go-left" },
    { "<leader>wj", "<C-w>j", desc = "go-bellow" },
    { "<leader>wk", "<C-w>k", desc = "go-above" },
    { "<leader>wl", "<C-w>l", desc = "go-right" },
    { "<leader>wm", "<cmd>lua require('maximizer').toggle()<CR>", desc = "maximize-toggle" },
    { "<leader>wq", "<cmd>wq<cr>", desc = "quit" },
    { "<leader>ws", "<C-w>s<C-w>j", desc = "split-down" },
    { "<leader>wv", "<C-w>v<C-w>l", desc = "split-right" },
    { "<leader>x", group = "trouble" },
    { "<leader>xd", "<cmd>Trouble toggle diagnostics<cr>", desc = "document" },
    { "<leader>xl", "<cmd>Trouble toggle lclist<cr>", desc = "loclist" },
    { "<leader>xq", "<cmd>Trouble toggle quickfix<cr>", desc = "quickfix" },
    { "<leader>xs", "<cmd>Trouble symbols<cr>", desc = "symbols" },
    { "<leader>xw", "<cmd>Trouble toggle diagnostics focus=true<cr>", desc = "workspace" },
    { "<leader>xx", "<cmd>Trouble diagnostics toggle focus=true filter.buf=0<cr>", desc = "document" },
    { "<leader>y", group = "yank" },
    { "<leader>yP", '"+P', desc = "paste before" },
    { "<leader>yj", "<Plug>(YankyCycleForward)", desc = "next yank" },
    { "<leader>yk", "<Plug>(YankyCycleBackward)", desc = "previous yank" },
    { "<leader>yp", '"+p', desc = "paste" },
    { "<leader>yy", '"+y', desc = "yank" },
  })

wk.add({
    {
      mode = { "v" },
      { "<leader>S", ":<C-U>sort<cr>", desc = "sort" },
      { "<leader>c", "<Plug>(comment_toggle_linewise_visual)", desc = "comment" },
      { "<leader>el", ":<C-u>call EvalLuaSelection()<CR>", desc = "eval-lua" },
      { "<leader>r", ":<C-U>REPLSendLines<cr>", desc = "send-to-repl" },
      { "<leader>s", "<cmd>ToggleTermSendVisualLines<cr>", desc = "send-visual" },
      { "<leader>y", '"+y', desc = "copy" },
      { "f", "<cmd><,>VBox<CR>", desc = "box-surround" },
    },
  })

wk.add({
    { "<C-w>b", "<cmd>lua ToggleWinBar()<cr>", desc = "win-bar" },
    { "<M-S-c>", ":lua require('dap').close()<cr>", desc = "close" },
    { "<M-c>", ":lua require('dap').continue()<cr>", desc = "continue" },
    { "<M-d>", ":DapToggleBreakpoint<CR>", desc = "bp-toggle" },
    { "<M-i>", ":lua require('dap').step_into()<cr>", desc = "step-into" },
    { "<M-l>", "<cmd>set nu! rnu!<cr>", desc = "line-numbers" },
    { "<M-o>", ":lua require('dap').step_out()<cr>", desc = "step-out" },
    { "<M-q><M-Q>", "<CMD>qa<CR>", desc = "close all" },
    { "<M-q><M-q>", "<CMD>wa<CR><CMD>qa!<CR>", desc = "force close" },
    { "<M-s>", ":lua require('dap').step_over()<cr>", desc = "step-over" },
  })

-- custom orgmode goto definition
api.nvim_create_autocmd({
	"FileType",
	"BufNewFile",
	"BufRead",
}, {
	pattern = "*.org",
	callback = function()
		keymap.set("n", "gd", function()
			local roam = require("org-roam")
			roam.goto_id()
		end)
	end,
})

-- better goto definition for csharp
api.nvim_create_autocmd({
	"BufNewFile",
	"BufRead",
}, {
	pattern = "*.cs",
	callback = function()
		keymap.set("n", "gd", function()
			require("omnisharp_extended").lsp_definitions()
		end)

		keymap.set("n", "vif", "viW%", { noremap = true, silent = true })
	end,
})
